apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-server
spec:
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - image: live4code/nginx-redis
        name: api-server
        ports:
        - name: http
          containerPort: 80
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.live4code.com
spec:
  selector:
    app: api-server
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: redis
    port: 6379
    targetPort: 6379
