FROM ubuntu:14.04

#install nodejs
RUN apt-get update
RUN apt-get -y install git python-software-properties python g++ make software-properties-common
RUN add-apt-repository -y ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get -y install nodejs

#install bower
RUN npm install -g bower

#phantomjs dependencies
RUN apt-get -y install libfreetype6 libfreetype6-dev libfontconfig
RUN npm install -g phantomjs@1.9.13

#selenium server need java
RUN apt-get -y install default-jre

#install other npm dependencies 
RUN npm install -g karma-cli
RUN npm install -g karma-phantomjs-launcher
RUN npm install -g karma-jasmine
RUN npm install -g http-server

#protractor e2e test
RUN npm install -g protractor@1.5.0

#install selenium webdriver
RUN webdriver-manager update

#nodegit dependencies
#RUN apt-get -y install cmake libssl-dev

# setup files and directory
RUN mkdir -p /root/live4code
ADD ./webrunner /root/live4code
RUN cd /root/live4code; npm install

EXPOSE 3005 8000

# setup start script for ghostdriver
ADD ./ghostdriver.sh /root/
RUN chmod 755 /root/ghostdriver.sh

# expose volume
VOLUME /var/tmp

# set env vars for discovery service
ENV DISCOVER api-server:3005,user-server:8000

ENV NODE_ENV development

# Installing supervisord
RUN apt-get install -y supervisor 
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Clean up APT when done.
#RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#use supervisor to controll what we want to start
CMD ["/usr/bin/supervisord"]







